### ISSUE TITLE
proposal: info message coloring

### ISSUE THREAD

**Issue by TorchedSammy** [shade-linux/shade-go#2]
currently there's two types of messages: error and success. what about the info type? like, the setup command just says that its beginning setup right. that should be a nice blue, which is what i suggest info messages be colored

**Comment by MCotocel** [comment]
Yeah that should be pretty easy to do. I'll add it tomorrow, since it's getting a bit late over here

**Comment by mTvare6** [comment]
Implemented in [(#311964b)](https://github.com/shade-linux/shade-go/commit/311964b49fe663c025c90c417bc45b9492f5c034)
